version: 15
jobs:
- name: Build tag
  jobExecutor: cyl3x-executor
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build
    runInContainer: true
    image: localhost:3016/cyl3x/godot-builder:latest
    interpreter: !DefaultInterpreter
      commands:
      - mkdir builds
      - godot -v . --export-pack "Linux" ./builds/server.pck
      - godot -v . --export "Linux" ./builds/Racing-game-@script:Version.txt@
      - godot -v . --export "Windows" ./builds/Racing-game-@script:Version.txt@.exe
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish Artifacts
    artifacts: builds/*
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CreateTagStep
    name: Tag
    tagName: '@script:Version.txt@'
    tagMessage: Publish @script:Version.txt@
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 500
  memoryRequirement: 256
  timeout: 3600
