version: 15
jobs:
- name: Tag build
  jobExecutor: cyl3x-executor
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build
    runInContainer: true
    image: localhost:3016/cyl3x/godot-builder:latest
    interpreter: !DefaultInterpreter
      commands:
      - bash
      - mkdir bin
      - cd bin
      - ''
      - echo "Init Project"
      - sed "s~build_date[[:space:]]*=[[:space:]]*\".*\"~build_date=\"$(date -d '+1
        minutes' -Iseconds)\"~g" -i ../project.godot
      - sed "s~build_number[[:space:]]*=[[:space:]]*\".*\"~build_number=\"@tag@\"~g"
        -i ../project.godot
      - sed "s~api_key[[:space:]]*=[[:space:]]*\".*\"~api_key=\"@secret:SECRET_API_KEY@\"~g"
        -i ../project.godot
      - '#godot --path .. --quiet -e -q'
      - '#sed ''s~binary_format/embed_pck[[:space:]]*=[[:space:]]*".*"~binary_format/embed_pck=false~g''
        -i ../export_presets.cfg'
      - ''
      - ''
      - echo "Build Linux binary"
      - godot --quiet --path .. --export "Linux/X11" bin/turismo-x-treme-@tag@.x86-64
      - '#'
      - '#godot --quiet --path .. --export-pack "Linux/X11" bin/turismo-x-treme-@tag@.pck'
      - ''
      - strip *.x86-64
      - zip linux-@tag@.zip *.x86-64 *.so *.pck
      - ''
      - echo "Build Server archive"
      - mkdir -p addons/bin/godot-sqlite/bin
      - cp -r ../addons/godot-sqlite/bin/osx ./addons/bin/godot-sqlite/bin
      - cp -r ../addons/godot-sqlite/bin/win64 ./addons/bin/godot-sqlite/bin
      - cp -r ../addons/godot-sqlite/bin/x11 ./addons/bin/godot-sqlite/bin
      - zip -r server-@tag@.zip *.pck addons
      - rm -rf *.x86-64 *.pck addons *.so
      - ''
      - echo "Build Windows binary"
      - godot --quiet --path .. --export "Windows" bin/turismo-x-treme-@tag@.exe
      - '#godot --quiet --path .. --export-pack "Windows" bin/turismo-x-treme-@tag@.pck'
      - ''
      - strip *.exe
      - zip windows-@tag@.zip *.exe *.dll *.pck
      - rm -rf *.exe *.dll
      - ''
      - chmod +x ../android/build/gradlew
      - echo "@secret:SECRET_RELEASE_KEYSTORE_BASE64@" | base64 -d > /root/release.keystore
      - sed 's~keystore/release[[:space:]]*=[[:space:]]*".*"~keystore/release = "/root/release.keystore"~g'
        -i ../export_presets.cfg
      - sed 's~keystore/release_password[[:space:]]*=[[:space:]]*".*"~keystore/release_password="@secret:SECRET_RELEASE_KEYSTORE_PASSWORD@"~g'
        -i ../export_presets.cfg
      - sed 's~keystore/release_user[[:space:]]*=[[:space:]]*".*"~keystore/release_user="@secret:SECRET_RELEASE_KEYSTORE_USER@"~g'
        -i ../export_presets.cfg
      - sed 's~version/name[[:space:]]*=[[:space:]]*".*"~version/name="@tag@"~g' -i
        ../export_presets.cfg
      - sed "s~version/code[[:space:]]*=[[:space:]]*\".*\"~version/code=\"$(date '+%s')\"~g"
        -i ../export_presets.cfg
      - sed 's~window/stretch/aspect[[:space:]]*=[[:space:]]*".*"~&\nwindow/stretch/shrink=1.2~'
        -i ../project.godot
      - ''
      - echo "Build Android release binary"
      - godot --quiet --path .. --export "Android" bin/turismo-x-treme-@tag@.apk
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish Artifacts
    artifacts: bin/*.apk bin/*.zip
    condition: ALWAYS
  triggers:
  - !TagCreateTrigger
    branches: master
    projects: cyl3x/godot-racing-game
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 500
  memoryRequirement: 256
  timeout: 3600
- name: Sync (Github)
  jobExecutor: cyl3x-shell-executer
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: sync
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - git config --global --unset http.extraHeader
      - git push -f https://cyl3x:@secrets:GITHUB_TOKEN@@@github.com/cyl3x/turismo-x-treme
        HEAD:master
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
    projects: cyl3x/godot-racing-game
  - !TagCreateTrigger
    tags: v*
    branches: master
    projects: cyl3x/godot-racing-game
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 500
  memoryRequirement: 256
  timeout: 3600
