version: 15
jobs:
- name: Build tag
  jobExecutor: cyl3x-executor
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build
    runInContainer: true
    image: localhost:3016/cyl3x/godot-builder:latest
    interpreter: !DefaultInterpreter
      commands:
      - mkdir builds
      - echo "Build Server .pck"
      - godot --quiet --path . --export-pack "Linux" builds/server-@param:Build Version@.pck
      - echo "Build Linux binary"
      - godot --quiet --path . --export "Linux" builds/Racing-game-@param:Build Version@.x86-64
      - echo "Build Windows binary"
      - godot --quiet --path . --export "Windows" builds/Racing-game-@param:Build
        Version@.exe
      - ''
      - chmod +x android/build/gradlew
      - ''
      - echo "@secret:SECRET_RELEASE_KEYSTORE_BASE64@" | base64 --decode > /root/release.keystore
      - sed 's_keystore/release[[:space:]]*=[[:space:]]*".*"_keystore/release = "/root/release.keystore"_g'
        -i export_presets.cfg
      - sed 's_keystore/release_password[[:space:]]*=[[:space:]]*".*"_keystore/release_password="@secret:SECRET_RELEASE_KEYSTORE_PASSWORD@"_g'
        -i export_presets.cfg
      - sed 's_keystore/release_user[[:space:]]*=[[:space:]]*".*"_keystore/release_user="@secret:SECRET_RELEASE_KEYSTORE_USER@"_g'
        -i export_presets.cfg
      - ''
      - godot --quiet --path . --export "Android" builds/Racing-game-@param:Build
        Version@.apk
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish Artifacts
    artifacts: builds/*
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CreateTagStep
    name: Tag
    tagName: '@param:Build Version@'
    tagMessage: Publish @param:Build Version@
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  paramSpecs:
  - !TextParam
    name: Build Version
    allowEmpty: false
    multiline: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 500
  memoryRequirement: 256
  timeout: 3600
