version: 15
jobs:
- name: Tag build
  jobExecutor: cyl3x-executor
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build
    runInContainer: true
    image: localhost:3016/cyl3x/godot-builder:latest
    interpreter: !DefaultInterpreter
      commands:
      - bash
      - mkdir bin
      - echo "Init Project"
      - godot --path . --quiet -e -q
      - ''
      - sed "s~build_date[[:space:]]*=[[:space:]]*\".*\"~build_date=\"$(date -d '+1
        minutes' -Iseconds)\"~g" -i project.godot
      - sed "s~build_number[[:space:]]*=[[:space:]]*\".*\"~build_number=\"@tag@\"~g"
        -i project.godot
      - sed "s~api_key[[:space:]]*=[[:space:]]*\".*\"~api_key=\"@secret:SECRET_API_KEY@\"~g"
        -i project.godot
      - ''
      - echo "Build Linux binary"
      - godot --quiet --path . --export "Linux/X11" bin/turismo-x-treme-@tag@.x86-64
      - echo "Export .pck"
      - godot --quiet --path . --export-pack "Linux/X11" bin/turismo-x-treme-@tag@.pck
      - echo "Build Windows binary"
      - godot --quiet --path . --export "Windows" bin/turismo-x-treme-@tag@.exe
      - ''
      - sed 's~window/stretch/aspect[[:space:]]*=[[:space:]]*".*"~&\nwindow/stretch/shrink=1.2~'
        -i project.godot
      - ''
      - chmod +x android/build/gradlew
      - ''
      - sed 's~version/name[[:space:]]*=[[:space:]]*".*"~version/name="@tag@"~g' -i
        export_presets.cfg
      - sed "s~version/code[[:space:]]*=[[:space:]]*\".*\"~version/code=\"$(date '+%s')\"~g"
        -i export_presets.cfg
      - ''
      - echo "@secret:SECRET_RELEASE_KEYSTORE_BASE64@" | base64 -d > /root/release.keystore
      - sed 's~keystore/release[[:space:]]*=[[:space:]]*".*"~keystore/release = "/root/release.keystore"~g'
        -i export_presets.cfg
      - sed 's~keystore/release_password[[:space:]]*=[[:space:]]*".*"~keystore/release_password="@secret:SECRET_RELEASE_KEYSTORE_PASSWORD@"~g'
        -i export_presets.cfg
      - sed 's~keystore/release_user[[:space:]]*=[[:space:]]*".*"~keystore/release_user="@secret:SECRET_RELEASE_KEYSTORE_USER@"~g'
        -i export_presets.cfg
      - ''
      - echo "Build Android release binary"
      - godot --quiet --path . --export "Android" bin/turismo-x-treme-@tag@.apk
      - ''
      - strip bin/Racing-game-@tag@.exe
      - strip bin/Racing-game-@tag@.x86-64
      - ''
      - cd bin
      - zip windows-@tag@.zip *.exe *.dll
      - zip linux-@tag@.zip *.x86-64 *.so
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish Artifacts
    artifacts: bin/*.apk bin/*.zip bin/*.pck
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    branches: master
    projects: cyl3x/godot-racing-game
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 500
  memoryRequirement: 256
  timeout: 3600
